Return an error when trying to create a record match run and the mast…
mitre/ptmatch pull request #19
Opened 2016-09-21 13:34 UTC by mlos100

…er record id or query record id is non-existent.  
https://github.com/mitre/ptmatchadapter/issues/12

2016-09-22 15:27 UTC, eedrummer commented on controllers/record_match_run.go
> +				"request":         string(reqBody)}).Info("About to submit request")
Very minor nit, but it appears that we are logging reqBody twice. Once in "reqBody" and once in "request".

2016-09-22 15:28 UTC, eedrummer requested changes

2016-09-26 10:50 UTC, mlos100 commented on controllers/record_match_run.go
> +				"request":         string(reqBody)}).Info("About to submit request")
Glad you caught it.  I was looking right past it even after making the change so the address of reqMatchRequest wasn't printed out.

2016-09-26 17:55 UTC, eedrummer approved these changes

2016-09-26 17:56 UTC, merged